version: 2

sources:
  - name: raw
    description: Raw tables from TheLook eCommerce dataset
    database: thelook
    schema: public
    tables:
      - name: orders
      - name: order_items
      - name: products
      - name: users

